### ISSUE TITLE
TP  03 : CNN déjà implémenté

### ISSUE THREAD

**Issue by thomasryck** [meteofrance/formation-deep-learning#12]
Il semblerait qu'il y ait une erreur dans le notebook "mnist_keras.ipynb", le CNN est déjà implémenté et la correction ne propose pas de modifier le nombre de convolution ou leur taille.
Peut être faudrait-il répéter la démarche qui est utilisé pour le NN "basique" ?

**Comment by lperez31** [comment]
Merci pour cette remontée. J'ai fait la modification.
